CREATE TABLE Product(
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(255) NOT NULL,
                        description varchar(4096),
                        price decimal check ( price > -1 ) DEFAULT 0.0,
                        inStock boolean DEFAULT false
);