ALTER TABLE Product ADD COLUMN "stock_quantity" INT DEFAULT 0;
ALTER TABLE Product RENAME COLUMN inStock TO in_stock;

CREATE TABLE Delivery(
                         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         title varchar(255),
                         product_id int NOT NULL REFERENCES product(id) ON DELETE CASCADE,
                         quantity int CHECK ( quantity > 0 )
);

CREATE TABLE Sale (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(255),
                      product_id int REFERENCES product(id) ON DELETE RESTRICT,
                      quantity int check ( quantity > 0 )
);