version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ms_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ms_db/ms_db

  ms_db:
    image: postgres:17
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1029384756"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ms_db -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  db-data: